FROM node:23-slim

USER root
WORKDIR /home/node

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    openssl \
    libssl-dev \
    procps && \
    rm -rf /var/lib/apt/lists/*

ENV PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true

COPY package*.json ./

RUN npm install

COPY prisma ./prisma/

RUN npx prisma generate

CMD ["npm", "run", "start:docker:dev"] 